spring:
  main:
    allow-circular-references: true

  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost/spring
    username: postgres
    password: 1122

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        jdbc:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    show-sql: true
