springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    url: /open-api.yaml
    show-extensions: true
    show-common-extensions: true
    try-it-out-enabled: true

spring:
  liquibase:
    enabled: true

  datasource:
    url: jdbc:postgresql://localhost/spring
    username: my_user
    password: 123

  jpa:
    generate-ddl: false # Все таблицы должны быть созданы из миграций, а не автоматически
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        jdbc:
          dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

    show-sql: true
