spring:
  main:
    allow-circular-references: true

  liquibase:
    enabled: true

  datasource:
    url: jdbc:h2:file:./db
#    initialization-mode: never

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: true

